### ISSUE TITLE
Warning: System.import() is deprecated

### ISSUE THREAD

**Issue by snikas** [paulbrom/hmr-redux-mapper#1]
getting the following warning after running reduxMapper command. Running Node v8.9.4

```
WARNING in ./app/scripts/reducerMap.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
```

**Comment by paulbrom** [comment]
Indeed!   I have fixed this by allowing a new -y command line option to specify the function name to use for import.  If not specified, it will default to System.import.   

If using redux-mapper.json, this is config property `systemImportCall`.

This has been fixed in 0.9.0
